spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/emr_patients_dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/emr

logging:
  level:
    com.cappymerida.patients: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    enabled: false