package com.cappymerida.domain.enums;

public enum EventType {
    PATIENT_REGISTERED,
    PATIENT_UPDATED,
    PATIENT_DEACTIVATED,
    PATIENT_ACTIVATED,
    PATIENT_DELETED,
    PATIENT_DEMOGRAPHICS_UPDATED,
    PATIENT_CONTACT_INFO_UPDATED,
    PATIENT_EMERGENCY_CONTACT_UPDATED
}
